# Generated by Django 6.0.4 on 2026-05-04 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgpaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.FloatField()),
                ('score', models.FloatField()),
                ('grade', models.CharField(max_length=2)),
                ('credit_point', models.FloatField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='cgpaapp.cgparecord')),
            ],
        ),
    ]
