# Generated by Django 6.0.4 on 2026-05-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgpaapp', '0002_semestercourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cgparecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='cgparecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cgparecord',
            name='gpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cgparecord',
            name='total_credit_point',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cgparecord',
            name='total_units',
            field=models.FloatField(default=0.0),
        ),
    ]
